<a href="https://colab.research.google.com/github/endar1y12/DS_1/blob/main/MSIB_MIKTI_Challenge_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Langkah pertama Import Library

In [ ]:
#import library numpy
import numpy as np
#import library pandas
import pandas as pd

In [ ]:
#membaca file dataset
df = pd.read_csv("/content/Property Listing Dataset.csv")

#menampilkan data
df

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Property Character,Size,Furnishing
0,"KLCC, Kuala Lumpur","RM 1,250,000",2+1,3.0,2.0,Serviced Residence,Built-up :,"1,335 sqft",Fully Furnished
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,NaN,Bungalow,Land area,6900 sqft,Partly Furnished
2,"Dutamas, Kuala Lumpur","RM 1,030,000",3,4.0,2.0,Condominium (Corner),Built-up :,"1,875 sqft",Partly Furnished
3,"Cheras, Kuala Lumpur",NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
4,"Bukit Jalil, Kuala Lumpur","RM 900,000",5,3.0,4.0,Condominium (Corner),Built-up :,"1,513 sqft",Partly Furnished
...,...,...,...,...,...,...,...,...,...
4995,"Sentul, Kuala Lumpur","RM 414,600",3,2.0,2.0,Serviced Residence,Built-up :,850 sqft,NaN
4996,"Ampang, Kuala Lumpur","RM 1,350,000",4,4.0,2.0,Semi-detached House (Intermediate),Built-up :,"3,600 sqft",Fully Furnished
4997,"Cheras, Kuala Lumpur","RM 483,300",2,2.0,2.0,Condominium (Intermediate),Land area,893-1195 sqft,Unfurnished
4998,"Cheras, Kuala Lumpur","RM 483,300",2,2.0,2.0,Condominium (Intermediate),Land area,893-1195 sqft,Unfurnished
4999,"Cheras, Kuala Lumpur","RM 439,600",3,2.0,2.0,Condominium,Land area,850-1000 sqft,Partly Furnished

#Langkah kedua check values disetiap columns dan jika ada column yang kosong isilah dengan N/A

In [ ]:
#cek values setiap column dan menampilkan jumlah values yang kosong
df.isnull().sum()

Location                 0
Price                   36
Rooms                  135
Bathrooms              158
Car Parks             1472
Property Type           25
Property Character     110
Size                   110
Furnishing             586
dtype: int64

In [ ]:
#mengisi column yang kosong dengan N/A
df = df.fillna('N/A')

#menampilkan data
df

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Property Character,Size,Furnishing
0,"KLCC, Kuala Lumpur","RM 1,250,000",2+1,3.0,2.0,Serviced Residence,Built-up :,"1,335 sqft",Fully Furnished
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,N/A,Bungalow,Land area,6900 sqft,Partly Furnished
2,"Dutamas, Kuala Lumpur","RM 1,030,000",3,4.0,2.0,Condominium (Corner),Built-up :,"1,875 sqft",Partly Furnished
3,"Cheras, Kuala Lumpur",N/A,N/A,N/A,2.0,N/A,N/A,N/A,N/A
4,"Bukit Jalil, Kuala Lumpur","RM 900,000",5,3.0,4.0,Condominium (Corner),Built-up :,"1,513 sqft",Partly Furnished
...,...,...,...,...,...,...,...,...,...
4995,"Sentul, Kuala Lumpur","RM 414,600",3,2.0,2.0,Serviced Residence,Built-up :,850 sqft,N/A
4996,"Ampang, Kuala Lumpur","RM 1,350,000",4,4.0,2.0,Semi-detached House (Intermediate),Built-up :,"3,600 sqft",Fully Furnished
4997,"Cheras, Kuala Lumpur","RM 483,300",2,2.0,2.0,Condominium (Intermediate),Land area,893-1195 sqft,Unfurnished
4998,"Cheras, Kuala Lumpur","RM 483,300",2,2.0,2.0,Condominium (Intermediate),Land area,893-1195 sqft,Unfurnished
4999,"Cheras, Kuala Lumpur","RM 439,600",3,2.0,2.0,Condominium,Land area,850-1000 sqft,Partly Furnished

#Langkah ketiga check data duplikasi pada setiap column dan hapus salah satu

In [ ]:
#mengecek data duplikasi
df.duplicated().sum()

68

In [ ]:
#Menghapus salah satu data yang duplikasi
df = df.drop_duplicates(keep = 'last')

In [ ]:
#mengecek data duplikasi
df.duplicated().sum()

0

In [ ]:
#mengisi column yang kosong dengan N/A
df = df.fillna('N/A')

#Langkah Keempat jika da value pada column Rooms,Bathrooms,Car Parks tidak menggunakan data number maka dihapus

In [ ]:
#mengecek setiap kolom apakah ada data yang bukan number
kolom_khusus = ['Rooms','Bathrooms','Car Parks']

#perulangan untuk mengecek setiap kolom
for kolom in kolom_khusus :
  try:
    pd.to_numeric(df[kolom])
    print("Semua nilai dalam kolom '{}' adalah angka.".format(kolom))
  except ValueError:
    print("ada nilai non-Number dalam kolom".format(kolom))

ada nilai non-Number dalam kolom
ada nilai non-Number dalam kolom
ada nilai non-Number dalam kolom

In [ ]:
#kolom yang ingin di cek
kolom_khusus = ['Rooms','Bathrooms','Car Parks']

#perulangan untuk menghapus data non numeric
for kolom in kolom_khusus:
  #konversi nilai nilai dalam kolom ke numeric
  df[kolom]= pd.to_numeric(df[kolom],errors='coerce')

#jika gagal konversi maka hapus
df = df.dropna()

#menyimpan data yang sudah dikonversi berhasil simpan ke dalam file baru
df.to_csv('Property_Listing_Dataset_clear.csv',index=False)

In [ ]:
#membaca file csv
df_new = pd.read_csv('Property_Listing_Dataset_clear.csv')

#menampilkan data file csv
df_new

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Property Character,Size,Furnishing
0,"Dutamas, Kuala Lumpur","RM 1,030,000",3.0,4.0,2.0,Condominium (Corner),Built-up :,"1,875 sqft",Partly Furnished
1,"Bukit Jalil, Kuala Lumpur","RM 900,000",5.0,3.0,4.0,Condominium (Corner),Built-up :,"1,513 sqft",Partly Furnished
2,"Taman Tun Dr Ismail, Kuala Lumpur","RM 5,350,000",6.0,5.0,4.0,Bungalow,Land area,7200 sqft,Partly Furnished
3,"Taman Tun Dr Ismail, Kuala Lumpur","RM 2,600,000",5.0,4.0,1.0,Semi-detached House,Land area,3600 sqft,Partly Furnished
4,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,700,000",4.0,3.0,4.0,2-sty Terrace/Link House (Intermediate),Land area,1900 sqft,Partly Furnished
...,...,...,...,...,...,...,...,...,...
3315,"Ampang, Kuala Lumpur","RM 2,200,000",6.0,6.0,2.0,2.5-sty Terrace/Link House (Corner),Land area,5403 sqft,Partly Furnished
3316,"Sentul, Kuala Lumpur","RM 414,600",3.0,2.0,2.0,Serviced Residence,Built-up :,850 sqft,NaN
3317,"Ampang, Kuala Lumpur","RM 1,350,000",4.0,4.0,2.0,Semi-detached House (Intermediate),Built-up :,"3,600 sqft",Fully Furnished
3318,"Cheras, Kuala Lumpur","RM 483,300",2.0,2.0,2.0,Condominium (Intermediate),Land area,893-1195 sqft,Unfurnished
3319,"Cheras, Kuala Lumpur","RM 439,600",3.0,2.0,2.0,Condominium,Land area,850-1000 sqft,Partly Furnished

In [ ]:
#mengecek setiap kolom apakah ada data yang bukan number
kolom_khusus = ['Rooms','Bathrooms','Car Parks']

#perulangan untuk mengecek setiap kolom
for kolom in kolom_khusus :
  try:
    pd.to_numeric(df[kolom])
    print("Semua nilai dalam kolom '{}' adalah angka.".format(kolom))
  except ValueError:
    print("ada nilai non-Number dalam kolom".format(kolom))

Semua nilai dalam kolom 'Rooms' adalah angka.
Semua nilai dalam kolom 'Bathrooms' adalah angka.
Semua nilai dalam kolom 'Car Parks' adalah angka.